version: "3"
services:
  consensus:
    image: gnosischain/lodestar-beacon:latest-chiado
    restart: always
    stop_grace_period: 1m
    volumes:
      - consensus-data:/var/lib/consensus
      - ./jwtsecret:/jwtsecret
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
    command: >
      --jwt-secret=/jwtsecret
      --execution.urls http://execution:8551
      --eth1.providerUrls http://execution:8545
      --dataDir /var/lib/data
      --rest "true"
      --rest.address 0.0.0.0
      --rest.port 4000
      --port 9000
      --logFileLevel debug
      --logFile /var/lib/data/beacon.log
      --logFileDailyRotate 5

  validator:
    image: gnosischain/lodestar-validator:latest-chiado
    restart: always
    volumes:
      - validator-data:/var/lib/data
      - ./keystores:/var/lib/keystores
    command: >
      --suggestedFeeRecipient ${FEE_RECIPIENT}
      --graffiti ${GRAFFITI}
      --importKeystores /var/lib/keystores
      --importKeystoresPassword /var/lib/keystores/password.txt
      --dataDir /var/lib/data
      --server http://consensus:4000
      --logFileLevel debug
      --logFile /var/lib/data/validator.log
      --logFileDailyRotate 

  execution:
    image: gnosischain/nethermind:latest-chiado
    restart: always
    stop_grace_period: 1m
    volumes:
      - execution-data:/var/lib/execution
      - ./jwtsecret:/jwtsecret
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
    command: >
      --JsonRpc.JwtSecretFile=/jwtsecret
      --JsonRpc.AdditionalRpcUrls="http://localhost:8551|http;ws|net;eth;subscribe;engine;web3;client"
      --JsonRpc.Enabled=true
      --JsonRpc.EnabledModules="net,eth,consensus,subscribe,web3,admin,txpool"
      --JsonRpc.Host=0.0.0.0
      --datadir=/var/lib/execution
      --Network.DiscoveryPort=30303
      --Network.P2PPort=30303

volumes:
  consensus-data:
  validator-data:
  execution-data:
